# tasks file for roles
---
- name: Install apache and php last version
  yum:
    name: "{{ item }}"
    state: present
  loop:  
    "{{ pkg }}"
- name: Démarrage du service apache
  systemd: 
    name: httpd
    state: started
- name: copie du fichier index.html dans /var/www/html
  copy:
   src: files/index.php
   dest: /var/www/html
- name: suppression du fichier index.html
  file:
   path: /var/www/html/index.html
   state: absent

- name: Modification du port 80 vers 8080 du serveur apache
  lineinfile:
   path: /etc/httpd/conf/httpd.conf
   regexp: '^Listen '
   insertafter: '^#Listen '
   line: Listen 8080
  notify:
   - restart_apache
  
- name: ajout du fichier de php de la configuraion d'acces a la db
  template:
    src: "db-config.php.j2"
    dest: /var/www/html/db-config.php
  notify:
   - restart_apache

## SERVEUR DE BASE DE DONNEES
- name: Ajout du dépots epel-release
  yum:
   name: epel-release
   state: present

- name: Installation de Mariadb et python2-PyMySQL
  yum:
   name:
    - mariadb-server
    - python2-PyMySQL
   state: present
  
- name: Start and activation du serveur Mariadb
  systemd:
    name: mariadb
    state: started
    enabled: yes
      
- name: Création du fichier client mariadb
  copy: 
    dest: /root/my.cnf
    content: | 
      [client]
      user=root 
      password=""

- name: Upload sql table config
  template:
    src: table.sql.j2
    dest: /tmp/table.sql

- name: Insert table dans mariadb
  mysql_db:
   name: "{{ mysql_dbname }}"
   state: present
   login_user: root
   login_password: ""
   state: import
   target: /tmp/table.sql

- name: "Create {{ mysql_user }} avec les privileges sur la db {{ mysql_dbname }}"
  mysql_user:
   login_user: root
   login_password: ""
   name: "{{ mysql_user }}"
   password: "{{mysql_password }}"
   priv: "{{ mysql_dbname }}.*:ALL"
   host: "{{ webserver_host }}"
   state: present

